[FEATURE] Add cObject SCHEMA to expose API to TypoScript
brotkrueml/schema pull request #89
Opened 2022-02-23 11:08 UTC by DanielSiepmann

Resolves: #88

2022-02-23 11:19 UTC, DanielSiepmann commented
Code is ready to review. This is draft as Documentation is still missing. Will add it.

2022-02-23 12:41 UTC, DanielSiepmann commented on Documentation/TypoScript/Index.rst
> +   See: :ref:`TypoScript Reference <t3ts:if>`.
Don't understand, but this link is not generated when I render locally.
But local rendering is extreme slow anyway, maybe there is something broken on my end. Would be cool if you could test it as well.

2022-02-23 12:42 UTC, DanielSiepmann commented on composer.json
> +		"typo3/cms-frontend": "^10.4.11 || ^11.5"
I don't think that's bad. But I guess one can also add this as dev dependency and suggestion.

2022-02-23 18:36 UTC, brotkrueml requested changes
Thanks for this great work :+1: Have some notes left ;-)

2022-02-23 18:36 UTC, brotkrueml commented on Classes/Frontend/TypoScriptToSchema.php
> +            $type->setProperty(
The DomainException is thrown, when using an unknown property. So this should be catched and logged. Also for other calls of setProperty.

2022-02-23 18:36 UTC, brotkrueml commented on Classes/Frontend/TypoScriptToSchema.php
> +                $type->setProperty(
This works not correct, example:

    page.300 = SCHEMA
    page.300 {
        type = Organization
        properties {
            brand = SCHEMA
            brand.id = my-brand
        }
    }

should return:

    {
        "@type": "Organization",
        "brand": {
            "@id": "my-brand"
        }
    }

but returns:

    {
        "@type": "Organization",
        "brand": [
            "my-brand"
        ]
    }

In PHP:

    $organization = TypeFactory::createType('Organization');
    $organization->setProperty('brand', new NodeIdentifier('my-brand'));
    $schemaManager->addType($organization);

The NodeIdentifier class is necessary in this case instead an array.

2022-02-23 18:36 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +        $this->importDataSet(__DIR__ . '/Fixtures/Database.xml');
I saw that in core the fixtures were migrated from XML to CSV recently. I don't like that, but I remember the discussion for switching to CSV.

2022-02-23 18:36 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +                'automaticBreadcrumbSchemaGeneration' => '1',
Maybe switch of the breadcrumb as it plays no role in our tests (displayed only on sub pages).

2022-02-23 18:36 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +    public function returnsNoSchemaForUnkownType(): void
Unkown => Unknown

2022-02-23 18:36 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +                    'page.10.type = Unkown',
Unkown => Unknown

2022-02-23 18:36 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +    public function returnsSchemaWithTypeAndId(): void
Can we use a data provider? Tests look same, only config and expected is different.

2022-02-23 18:36 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +}
Need some more tests, like only id given for a sub type (see above). Also would like to see the handling (logging) of non-existing types and properties.

2022-02-23 18:36 UTC, brotkrueml commented on composer.json
> +		"typo3/cms-frontend": "^10.4.11 || ^11.5"
Strictly speaking it is not necessary as requirement (when not using the new cObj), as core doesn't rely on it. But the minimal package requires it, so it's okay for me.

2022-02-24 05:46 UTC, DanielSiepmann commented on Documentation/TypoScript/Index.rst
> +   See: :ref:`TypoScript Reference <t3ts:if>`.
Already did that, but didn't help.

2022-02-24 05:57 UTC, DanielSiepmann commented on Documentation/TypoScript/Index.rst
> +   See: :ref:`TypoScript Reference <t3ts:if>`.
Ah looks like routing of Docker was influenced by a VPN connection. Worked this morning when I wasn't inside VPN. Also speeds up rendering. Probably because Docker now can fetch the inventories and don't wait until timeouts.

2022-02-24 05:59 UTC, DanielSiepmann commented on Classes/Frontend/SchemaContentObject.php
> +        $GLOBALS['TYPO3_CONF_VARS']['FE']['ContentObjects']['SCHEMA'] = static::class;
Will change, just an explanation why I follow that approach:
- I don't like to clutter the (more or less legacy ext_localconf.php).
- I also don't like to have features cluttered all over the code ;) I like self-contained classes for a single feature. But that will probably change anyway. I would like to have more registries auto configured through interfaces. But seems like we are adding more and more dedicated configuration files. Which are easier to be filled from ext_localconf.php, e.g. via rector or manually.

2022-02-24 06:01 UTC, DanielSiepmann commented on Classes/Frontend/TypoScriptToSchema.php
> +            // Do not break production sites, catch exception and return nothing.
Will do in a dedicated commit which will also add corresponding test case.
That should also extend existing test cases to ensure nothing unexpected gets logged.

2022-02-24 06:02 UTC, DanielSiepmann commented on Classes/Frontend/TypoScriptToSchema.php
> +            $type->setProperty(
Will add that together with logging of wrong Type usage.

2022-02-24 06:03 UTC, DanielSiepmann commented on Classes/Frontend/TypoScriptToSchema.php
> +                $type->setProperty(
Will add a dedicated test in separate commit, with fix.

2022-02-24 06:04 UTC, DanielSiepmann commented on Tests/Functional/TypoScriptToSchemaTest.php
> +        $this->importDataSet(__DIR__ . '/Fixtures/Database.xml');
I'll adapt. I hate this CSV as it isn't a human friendly format and People probably only use it due to nice IDE features.

2022-02-24 06:58 UTC, brotkrueml commented on Tests/Functional/TypoScriptToSchemaTest.php
> +        $this->importDataSet(__DIR__ . '/Fixtures/Database.xml');
Yes, me too, I am fine with XML, just want to make a hint ;-)

2022-02-24 07:02 UTC, DanielSiepmann commented on Classes/Frontend/TypoScriptToSchema.php
> +            $type->setProperty(
Added logging and handling of unknown properties with tests in ef04436.

2022-02-24 07:02 UTC, DanielSiepmann commented on Classes/Frontend/TypoScriptToSchema.php
> +            // Do not break production sites, catch exception and return nothing.
Added logging with tests in ef04436.

2022-02-24 07:03 UTC, DanielSiepmann commented on Tests/Functional/TypoScriptToSchemaTest.php
> +}
Logging was added, together with tests.
The only id thing will be added in separated commit.

Do you miss further tests?

2022-02-24 08:09 UTC, DanielSiepmann commented on Classes/Frontend/TypoScriptToSchema.php
> +                $type->setProperty(
Adjusted expectation of existing test.
Adapted code to use NodeIdentifier.

2022-02-25 15:53 UTC, brotkrueml reviewed
Made same additions, maybe you can have a look. Added also some more test cases.

Infection is a beast, don't know why it is sometimes running in errors, sometimes not. Looks like dependencies in the tests. But this is not a blocker for this PR.

2022-02-28 12:07 UTC, DanielSiepmann commented
Thanks for all the efforts. All changes look good to me :)

2022-02-28 18:32 UTC, merged